FROM --platform=$TARGETPLATFORM debian:stable-slim@sha256:0d97731c59efdde181e19c4a5ec22d16e9eefcb73175598b9b7bae712c7214eb AS inngest
RUN apt-get update && apt-get upgrade -y && apt-get install -y ca-certificates tzdata curl && update-ca-certificates
RUN groupadd -g 1000 inngest && useradd -u 1000 -g inngest -s /usr/sbin/nologin -M inngest
COPY inngest /bin/inngest
USER inngest
CMD ["inngest"]
