FROM --platform=$TARGETPLATFORM debian:stable-slim@sha256:1710bde34461551a19a47c787885ec9ad7058d9a5bead2affb8d088fa2f8502b AS inngest
RUN apt-get update && apt-get upgrade -y && apt-get install -y ca-certificates tzdata curl && update-ca-certificates
RUN groupadd -g 1000 inngest && useradd -u 1000 -g inngest -s /usr/sbin/nologin -M inngest
COPY inngest /bin/inngest
USER inngest
CMD ["inngest"]
