name: Dev Server UI

on:
  push:
    branches: [main]
    paths:
      - "ui/**"
      - "pkg/coreapi/**/*.graphql"
  pull_request:
    paths:
      - "ui/**"
      - "pkg/coreapi/**/*.graphql"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: "11.24.0"
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: "24"
      - name: Install
        run: pnpm install --frozen-lockfile
        working-directory: ui/apps/dev-server-ui
      - name: Build
        run: pnpm build
        working-directory: ui/apps/dev-server-ui
