name: UI

on:
  push:
    branches: [main]
    paths:
      - "ui/**"
  pull_request:
    paths:
      - "ui/**"

permissions:
  contents: read

jobs:
  # A flag we can use to warn us of critical known issues in the chain. This
  # should be caught in a number of places (including GitHub as CVEs), but we
  # also perform a check here.
  audit:
    name: pnpm security audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: "11.24.0"
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: "24"
      # Optional dependencies are packages like frameworks, which are actually
      # peer dependencies and are not installed in every usage, so we omit them
      # here and only check what's shipped directly by us.
      - run: pnpm audit --audit-level=critical --prod --no-optional --ignore-registry-errors
        working-directory: ui

